- name: Install dan jalankan web server NGINX (Ubuntu)
  hosts: ubuntu
  become: yes
  gather_facts: no

  tasks:
    - name: Update repository apt
      ansible.builtin.apt:
        update_cache: yes

    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: Start dan enable nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
